
on:
  push:
    branches: ['1.12.2']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 4.9
        arguments: test

