on:
  push:
    branches: ['1.16.x']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.3
        arguments: test --info
        cache-read-only: ${{ github.ref != 'refs/heads/1.16.x' }}
